Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@gassaf1973 
nanuchi
/
my-project
3
23168
Code
Issues
Pull requests
13
Actions
Projects
Wiki
Security
Insights
my-project/.github/workflows/ci.yml
@nanuchi
nanuchi Update ci.yml
Latest commit b109fe9 on 30 Sep 2020
 History
 1 contributor
38 lines (28 sloc)  902 Bytes
  
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
